#camera_ids: ["0","1","2"]
#camera_names: ["gopro_0","rs_1","webcam_2"]
#camera_refs : ["gopro_0","rs_1","webcam_2"]
#camera_types:
#  "gopro_0": "gopro"
#  "rs_1": "rs"
#  "webcam_2": "webcam"

#img_h: 480
#img_w: 640
#
#camera_name_conversion:
#  "gopro_0": "agentview0"
#  "rs_1": "agentview1"
#  "webcam_2": "agentview2"


#obs_key_mapping:
#  camera_0_color: agentview_rgb
#  camera_0_depth: agentview_depth
#
#  gripper_states: gripper_states
#  joint_states: joint-states
#  ee_states: ee_states
#  xyz: xyz

# camera_ids: ["0"]
# camera_names: ["gopro_0"]
# camera_refs : ["gopro_0"]
# camera_types:
#   "gopro_0": "gopro"

# img_h: 480
# img_w: 640

# camera_name_conversion:
#   "gopro_0": "agentview0"

# obs_key_mapping:
#   camera_0_color: agentview_rgb
#   camera_0_depth: agentview_depth

#   gripper_states: gripper_states
#   joint_states: joint-states
#   ee_states: ee_states
#   xyz: xyz


#  camera_ids: ["1","2"]
#  camera_names: ["webcam_1","webcam_2"]
#  camera_refs: ["webcam_1","webcam_2"]
#  camera_types:
#    "webcam_1": "webcam"
#    "webcam_2": "webcam"

#  img_h: 480
#  img_w: 640

#  camera_name_conversion:
#    "webcam_1": "agentview1"
#    "webcam_2": "agentview2"

#  obs_key_mapping:
#    camera_0_color: agentview_rgb
#    camera_0_depth: agentview_depth

#    gripper_states: gripper_states
#    joint_states: joint-states
#    ee_states: ee_states


 camera_ids: ["1"]
 camera_names: ["zed_1"]
 camera_refs: ["zed_1"]
 camera_types:
   "zed_1": "zed"

 img_h: 480
 img_w: 640

 camera_name_conversion:
   "zed_1": "agentview1"

 obs_key_mapping:
   camera_0_color: agentview_rgb
   camera_0_depth: agentview_depth

   gripper_states: gripper_states
   joint_states: joint-states
   ee_states: ee_states